name: Export file

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: webfactory/ssh-agent@v0.5.3
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Build
      run: |
        sudo apt update
        sudo apt install cargo
        cargo install monolith
        monolith https://garv-shah.github.io/EducationPerfected/settings/ -o output.html
        git clone git@github.com:KEN-2000l/EducationPerfected.git
        git config --global user.name "Settings Website Bot"
        git config --global user.email "<>"
        rm -rf EducationPerfected/output.txt
        mv output.html EducationPerfected/output.txt
        cd EducationPerfected
        git add .
        git commit -m "Automatically Updated Website"
        git push origin main
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: settings
        path: output.txt
